import os
import json
import paramiko
import getpass

# --- Server Configuration ---
# Replace these with your server's details.
# It's better to use environment variables or a config file for sensitive data.
HOSTNAME = "1ink.us"
PORT = 22  # Default SFTP/SSH port
USERNAME = "ford442"

# --- Project Configuration ---
# The local directory to upload from.
LOCAL_DIRECTORY = "build"
# The directory on the server where the files should go (e.g., 'public_html/wasm-game').
REMOTE_DIRECTORY = "streetview"

def make_config_js(api_key: str) -> str:
    """Return the content of config.js with the given API key safely JSON-encoded."""
    return (
        "// Runtime configuration — auto-generated by deploy.py\n"
        "// Do NOT edit on the server; re-deploy to update.\n"
        f"window.MAPS_API_KEY = {json.dumps(api_key)};\n"
    )

def upload_directory(sftp_client, local_path, remote_path):
    """
    Recursively uploads a directory and its contents to the remote server.
    """
    print(f"Creating remote directory: {remote_path}")
    try:
        # Create the target directory on the server if it doesn't exist.
        sftp_client.mkdir(remote_path)
    except IOError:
        # Directory already exists, which is fine.
        print(f"Directory {remote_path} already exists.")

    for item in os.listdir(local_path):
        local_item_path = os.path.join(local_path, item)
        remote_item_path = f"{remote_path}/{item}"

        if os.path.isfile(local_item_path):
            print(f"Uploading file: {local_item_path} -> {remote_item_path}")
            sftp_client.put(local_item_path, remote_item_path)
        elif os.path.isdir(local_item_path):
            # If it's a directory, recurse into it.
            upload_directory(sftp_client, local_item_path, remote_item_path)

def main():
    """
    Main function to connect to the server and start the upload process.
    """
    # Prefer the DEPLOY_PASSWORD env var; fall back to an interactive prompt.
    password = os.environ.get("DEPLOY_PASSWORD") or getpass.getpass(f"Enter password for {USERNAME}@{HOSTNAME}: ")

    # --- API Key injection (CRITICAL for avoiding "can't load Google Maps correctly") ---
    # Read MAPS_API_KEY from the environment.  If set, the deploy script writes
    # a config.js with the real key into the build/ directory before uploading.
    # This is the PREFERRED path for production because it does not require a
    # matching build-time REACT_APP_MAPS_API_KEY and lets you target specific hosts.
    maps_api_key = os.environ.get("MAPS_API_KEY", "").strip()

    # Also read what the *build* baked in (for diagnostics only)
    baked_key = ""
    baked_config = os.path.join(LOCAL_DIRECTORY, "config.js")
    if os.path.exists(baked_config):
        try:
            with open(baked_config, "r", encoding="utf-8") as f:
                content = f.read()
                if "AIza" in content:
                    # crude extraction for warning
                    import re
                    m = re.search(r'(AIzaSy[0-9A-Za-z_-]{30,})', content)
                    if m:
                        baked_key = m.group(1)
        except Exception:
            pass

    if maps_api_key:
        config_js_path = os.path.join(LOCAL_DIRECTORY, "config.js")
        print(f"🔑 Injecting MAPS_API_KEY into {config_js_path} (runtime override)...")
        with open(config_js_path, "w", encoding="utf-8") as f:
            f.write(make_config_js(maps_api_key))
        print("   This key will be used on the live site (window.MAPS_API_KEY).")
        print("   IMPORTANT: The key's Google Cloud HTTP referrer restrictions MUST include the target host.")
        print("   Example allowed referrers for the demo hosts:\n"
              "     https://test.1ink.us/*\n"
              "     https://go.1ink.us/*\n"
              "     http://localhost:3000/*")
    else:
        print(
            "\n" + "!" * 70 + "\n"
            "⚠️  CRITICAL WARNING: MAPS_API_KEY env var NOT provided to deploy.py\n"
            "   The build/ will be uploaded with whatever key was baked at `npm run build` time\n"
            "   (from .env or the shell's REACT_APP_MAPS_API_KEY) PLUS the committed\n"
            "   public/config.js (which is now empty by default).\n"
            "\n"
            "   If the baked key's referrer restrictions do not whitelist the exact\n"
            "   production origin (test.1ink.us or go.1ink.us), visitors will see the\n"
            "   classic Google error: \"This page can't load Google Maps correctly\".\n"
            "\n"
            "   Recommended:  MAPS_API_KEY=your_real_key python deploy.py\n"
            "   Also ensure the key has billing enabled + Maps JavaScript + Directions APIs.\n" +
            "!" * 70 + "\n"
        )
        if baked_key:
            print(f"   Build-time key detected in build/config.js (masked): {baked_key[:10]}...{baked_key[-6:]}")
            print("   This key will be the fallback if runtime config.js fails to load.\n")

    transport = None
    sftp = None
    try:
        # Establish the SSH connection
        transport = paramiko.Transport((HOSTNAME, PORT))
        print("Connecting to server...")
        transport.connect(username=USERNAME, password=password)
        print("Connection successful!")

        # Create an SFTP client from the transport
        sftp = paramiko.SFTPClient.from_transport(transport)
        print(f"Starting upload of '{LOCAL_DIRECTORY}' to '{REMOTE_DIRECTORY}'...")

        # Start the recursive upload
        upload_directory(sftp, LOCAL_DIRECTORY, REMOTE_DIRECTORY)

        print("\n✅ Deployment complete!")
        print("   Next steps if you see Google Maps errors on the live site:")
        print("   1. Visit https://test.1ink.us/streetview/config.js (should 200 with your key)")
        print("   2. In GCP Console, verify the key has HTTP referrers for test.1ink.us/* and go.1ink.us/*")
        print("   3. Confirm billing account is linked to the project and no payment issues")
        print("   4. Confirm Maps JavaScript API and Directions API are enabled for the key")

    except Exception as e:
        print(f"❌ An error occurred: {e}")
    finally:
        # Ensure the connection is closed
        if sftp:
            sftp.close()
        if transport:
            transport.close()
        print("Connection closed.")

if __name__ == "__main__":
    if not os.path.exists(LOCAL_DIRECTORY):
        print(f"Error: Local directory '{LOCAL_DIRECTORY}' not found. Did you run 'npm run build' first?")
    else:
        main()

