/**
 * 3D LUT helpers — HALD strip PNGs → texture_3d volumes.
 *
 * Layout is textures, not weather uniforms (the 40-float buffer stays full).
 * Identity / missing LUT = skip sampling so default ACES pixels do not change.
 *
 * Strip convention: width = size*size, height = size. Voxel (x,y,z) lives at
 * pixel (z * size + x, y). Generated by scripts/gen-look-luts.mjs.
 */

import { LOOK_PACKS, type LookId, type LookPack } from '../config/lookPacks';
import type { QualityLevel } from '../config/visualPresets';

export const LUT_SIZE_DEFAULT = 32;
export const LUT_SIZE_LOW = 16;

export interface LutVolume {
  size: number;
  /** RGBA8, size³ voxels, z-major then y then x. */
  pixels: Uint8Array;
  lookId: LookId | 'identity';
}

const LUMA = { r: 0.2126, g: 0.7152, b: 0.0722 };

function clamp01(v: number): number {
  return Math.min(1, Math.max(0, v));
}

/** Shader-space grade (uniforms already shifted so 0 = identity). */
export function applyLookGradeRgb(
  r: number,
  g: number,
  b: number,
  pack: Pick<LookPack, 'vibrance' | 'saturation' | 'contrast' | 'exposure' | 'temperature' | 'tint'>,
): [number, number, number] {
  const vibrance = pack.vibrance - 1;
  const saturation = pack.saturation - 1;
  const contrast = pack.contrast - 1;
  let cr = r;
  let cg = g;
  let cb = b;

  const luma0 = cr * LUMA.r + cg * LUMA.g + cb * LUMA.b;
  const maxC = Math.max(cr, cg, cb);
  const sat = maxC - luma0;
  const vMul = vibrance * (1 - sat);
  cr += (cr - luma0) * vMul;
  cg += (cg - luma0) * vMul;
  cb += (cb - luma0) * vMul;

  const luma1 = cr * LUMA.r + cg * LUMA.g + cb * LUMA.b;
  const sAmt = 1 + saturation;
  cr = luma1 + (cr - luma1) * sAmt;
  cg = luma1 + (cg - luma1) * sAmt;
  cb = luma1 + (cb - luma1) * sAmt;

  cr = (cr - 0.5) * (1 + contrast) + 0.5;
  cg = (cg - 0.5) * (1 + contrast) + 0.5;
  cb = (cb - 0.5) * (1 + contrast) + 0.5;

  const kelvin = 6500 + pack.temperature * 5000;
  const kRgb = kelvinToRgb(kelvin);
  const nRgb = kelvinToRgb(6500);
  const tint = pack.tint;
  cr *= (kRgb[0] / nRgb[0]) * (1 + tint * 0.05);
  cg *= (kRgb[1] / nRgb[1]) * (1 + tint * 0.1);
  cb *= (kRgb[2] / nRgb[2]) * (1 + tint * 0.05);

  const exp = 2 ** pack.exposure;
  return [clamp01(cr * exp), clamp01(cg * exp), clamp01(cb * exp)];
}

function kelvinToRgb(kelvin: number): [number, number, number] {
  const temp = Math.min(40000, Math.max(1000, kelvin)) / 100;
  let r = 255;
  let g = 255;
  let b = 255;
  if (temp > 66) {
    r = 329.698727446 * (temp - 60) ** -0.1332047592;
  }
  if (temp <= 66) {
    g = 99.4708025861 * Math.log(temp) - 161.1195681661;
  } else {
    g = 288.1221695283 * (temp - 60) ** -0.0755148492;
  }
  if (temp < 66) {
    b = temp > 19 ? 138.5177312231 * Math.log(temp - 10) - 305.0447927307 : 0;
  }
  return [clamp01(r / 255), clamp01(g / 255), clamp01(b / 255)];
}

export function buildLutVolume(
  lookId: LookId | 'identity',
  size: number = LUT_SIZE_DEFAULT,
): LutVolume {
  const n = size;
  const pixels = new Uint8Array(n * n * n * 4);
  const pack = lookId === 'identity' || lookId === 'clear' ? LOOK_PACKS.clear : LOOK_PACKS[lookId];
  const identity = lookId === 'identity' || lookId === 'clear';
  let i = 0;
  for (let z = 0; z < n; z++) {
    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        const r = n === 1 ? 0 : x / (n - 1);
        const g = n === 1 ? 0 : y / (n - 1);
        const b = n === 1 ? 0 : z / (n - 1);
        const out = identity ? [r, g, b] as const : applyLookGradeRgb(r, g, b, pack);
        pixels[i++] = Math.round(out[0] * 255);
        pixels[i++] = Math.round(out[1] * 255);
        pixels[i++] = Math.round(out[2] * 255);
        pixels[i++] = 255;
      }
    }
  }
  return { size: n, pixels, lookId: identity ? 'identity' : lookId };
}

/** Slice a HALD strip (width = size², height = size) into a volume. */
export function sliceHaldStrip(
  width: number,
  height: number,
  rgba: Uint8ClampedArray | Uint8Array,
  lookId: LookId | 'identity' = 'identity',
): LutVolume {
  if (height < 1 || width !== height * height) {
    throw new Error(`Expected HALD strip size²×size, got ${width}×${height}`);
  }
  const size = height;
  const pixels = new Uint8Array(size * size * size * 4);
  let i = 0;
  for (let z = 0; z < size; z++) {
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const px = z * size + x;
        const src = (y * width + px) * 4;
        pixels[i++] = rgba[src] ?? 0;
        pixels[i++] = rgba[src + 1] ?? 0;
        pixels[i++] = rgba[src + 2] ?? 0;
        pixels[i++] = 255;
      }
    }
  }
  return { size, pixels, lookId };
}

export function lutSizeForQuality(quality: QualityLevel): number {
  return quality === 'low' ? LUT_SIZE_LOW : LUT_SIZE_DEFAULT;
}

export function shouldLoadLookLut(lookId: LookId | null | undefined): lookId is LookId {
  return typeof lookId === 'string' && lookId !== 'clear' && lookId in LOOK_PACKS;
}

function publicUrl(file: string): string {
  const base = (typeof process !== 'undefined' && process.env.PUBLIC_URL) || './';
  const prefix = base.endsWith('/') ? base : `${base}/`;
  return `${prefix}${file}`;
}

/**
 * Fetch a look's HALD PNG and slice it. Returns null for clear/identity so
 * the weather pass keeps today's ACES-only path (pixel-equal).
 */
export async function fetchLookLutVolume(
  lookId: LookId | null | undefined,
  quality: QualityLevel = 'high',
): Promise<LutVolume | null> {
  if (!shouldLoadLookLut(lookId)) return null;
  if (typeof fetch !== 'function') return buildLutVolume(lookId, lutSizeForQuality(quality));

  const url = publicUrl(`luts/${lookId}.png`);
  try {
    const res = await fetch(url);
    if (!res.ok) return buildLutVolume(lookId, lutSizeForQuality(quality));
    const blob = await res.blob();
    if (typeof createImageBitmap !== 'function') {
      return buildLutVolume(lookId, lutSizeForQuality(quality));
    }
    const bmp = await createImageBitmap(blob);
    const canvas = document.createElement('canvas');
    canvas.width = bmp.width;
    canvas.height = bmp.height;
    const ctx = canvas.getContext('2d');
    if (!ctx) return buildLutVolume(lookId, lutSizeForQuality(quality));
    ctx.drawImage(bmp, 0, 0);
    const img = ctx.getImageData(0, 0, bmp.width, bmp.height);
    bmp.close();
    const volume = sliceHaldStrip(img.width, img.height, img.data, lookId);
    const want = lutSizeForQuality(quality);
    if (volume.size === want) return volume;
    return buildLutVolume(lookId, want);
  } catch {
    return buildLutVolume(lookId, lutSizeForQuality(quality));
  }
}
