import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.join(__dirname, '..', '..');

// Keep this list in sync with WEATHER_POST_FRAGMENTS in
// scripts/gen-weather-post-shader.mjs.
const FRAGMENTS = [
    'public/shaders/weather-post/01-foundation.wgsl',
    'public/shaders/weather-post/02-weather-fx.wgsl',
    'public/shaders/weather-post/03-night-and-composite.wgsl',
];

describe('weather-post.wgsl source split', () => {
    it('matches the concatenation of its public/shaders/weather-post/ fragments', () => {
        // public/shaders/weather-post.wgsl is generated by
        // scripts/gen-weather-post-shader.mjs from the fragments above (split
        // by responsibility because the combined file had grown past ~1,100
        // lines). This fails if someone hand-edits the generated file, or
        // edits a fragment without running `npm run gen:weather-shader` —
        // both would let the fragments and the shipped shader silently drift
        // apart.
        const committed = fs.readFileSync(path.join(repoRoot, 'public/shaders/weather-post.wgsl'), 'utf8');
        const regenerated = FRAGMENTS.map((relPath) => fs.readFileSync(path.join(repoRoot, relPath), 'utf8')).join('');

        expect(committed).toBe(regenerated);
    });
});
